Move from `std::map` of `unique_ptr` to `absl::flat_hash_map`.
The ``older'' versions of MSVC compiler are refusing to have

  `std::vector<std::map<absl::string_view, std::unique_ptr<...>>>`

as a concept attempting a copy of elements of `std::map` which in this case is
not copyable:

```
026-03-07T22:45:28.1249233Z ERROR: D:/a/openfst/openfst/openfst/test/BUILD.bazel:20:8: Compiling openfst/test/equivalent_test.cc failed: (Exit 2): cl.exe failed: error executing CppCompile command (from cc_test rule target //openfst/test:equivalent_test) C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.44.35207\bin\HostX64\x64\cl.exe @bazel-out/x64_windows-opt/bin/openfst/test/_objs/equivalent_test/equivalent_test.obj.params
2026-03-07T22:45:28.1252704Z C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.44.35207\include\xmemory(732): error C2280: 'std::pair<const std::string_view,std::unique_ptr<fst::VectorFst<fst::StdArc,fst::VectorState<Arc,std::allocator<Arc>>>,std::default_delete<fst::VectorFst<fst::StdArc,fst::VectorState<Arc,std::allocator<Arc>>>>>>::pair(const std::pair<const std::string_view,std::unique_ptr<fst::VectorFst<fst::StdArc,fst::VectorState<Arc,std::allocator<Arc>>>,std::default_delete<fst::VectorFst<fst::StdArc,fst::VectorState<Arc,std::allocator<Arc>>>>>> &)': attempting to reference a deleted function
2026-03-07T22:45:28.1254731Z         with
2026-03-07T22:45:28.1254895Z         [
2026-03-07T22:45:28.1255060Z             Arc=fst::StdArc
2026-03-07T22:45:28.1255524Z         ]
```

Moving to `flat_hash_map` fixes this. Also, some minor cosmetic improvements to how the maps and vector are filled
in.

PiperOrigin-RevId: 880831576